name: Verify Activation
on:
  workflow_dispatch: {}
jobs:
  activate:
    name: Activate license
    runs-on: ubuntu-latest
    steps:
      - name: Unity - Activate
        uses: game-ci/unity-activate@v2.0.0
